package com.wp.miaoshaproject.dao;

import com.wp.miaoshaproject.dataobject.ItemStockDO;

import org.apache.ibatis.annotations.Param;

public interface ItemStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jun 04 17:23:01 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jun 04 17:23:01 CST 2019
     */
    int insert(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jun 04 17:23:01 CST 2019
     */
    int insertSelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jun 04 17:23:01 CST 2019
     */
    ItemStockDO selectByPrimaryKey(Integer id);
    
    ItemStockDO selectByItemId(Integer ItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jun 04 17:23:01 CST 2019
     */
    int updateByPrimaryKeySelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jun 04 17:23:01 CST 2019
     */
    int updateByPrimaryKey(ItemStockDO record);

    /**
     *返回值是受影响的条目数，减库存成功返回1，不成功返回0
     */
    int decreaseStock(@Param("itemId")Integer itemId, @Param("amount") Integer amount);
}